name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  RESOURCE_GROUP: "terrarg02dev"
  ACR_LOGIN_SERVER: "terraacr01dev.azurecr.io"
  VERSION: v1-${{ github.run_number }}

jobs:
  buildImage:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Docker Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login terraacr01dev.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
            
      - name: Build Docker Image
        run: |
          docker build -t ${{env.ACR_LOGIN_SERVER}}/netwin:${{ env.VERSION }} . 
          docker push ${{env.ACR_LOGIN_SERVER}}/netwin:${{ env.VERSION }}
          
      # How to automatically update the image tag in app service directly to production  
      # - name: Update App Service
      #   run: |
      #     az webapp config container set `
      #       --resource-group vishaltestrg01 `
      #       --name webaptest01 `
      #       --container-image-name terraacr01dev.azurecr.io/netwin:${{ env.VERSION }}

      
      # deploy to staging slot
      - name: Deploy to Staging Slot
        run: |
          az webapp config container set `
            --resource-group vishaltestrg01 `
            --name webaptest01 `
            --slot swap `
            --container-image-name terraacr01dev.azurecr.io/netwin:${{ env.VERSION }}
      #Restart staging slot
      - name: Restart Staging Slot
        run: |
          az webapp restart `
            --resource-group vishaltestrg01 `
            --name webaptest01 `
            --slot swap

      #wait for container start up
      - name: Wait for Startup
        shell: powershell
        run: |
          Start-Sleep -Seconds 30

      #Health check
      - name: Health Check
        shell: powershell
        run: |
          $response = Invoke-WebRequest `
            -Uri "https://webaptest01-swap-faeybheegbcahvd6.centralindia-01.azurewebsites.net/" `
            -UseBasicParsing
      
          if ($response.StatusCode -ne 200)
          {
              Write-Error "Health Check Failed"
              exit 1
          }
      #Swap to production
      - name: Swap Slot
        if: success()
        run: |
          az webapp deployment slot swap `
            --resource-group vishaltestrg01 `
            --name webaptest01 `
            --slot swap `
            --target-slot production
